#!/bin/bash

supervisord -c /etc/supervisor/supervisord.conf 1>&2 &

echo "waiting for services to start" 1>&2
sleep 3
supervisorctl status
while ([[ $i > 1 ]] && supervisorctl status | grep -v RUNNING) ; do
   echo "waiting for services to start" 1>&2
   sleep 3
done

exec go-crond --include=/etc/cron.d/ --verbose root:/root/cron www-data:/var/www/cron

exec $@
